version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/db

