version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  basic_site:
    image: basic_site:latest
    volumes:
      - ./db:/db
      - ./.env:/.env

